###
GET http://localhost:3000/api/getall

###
POST http://localhost:3000/api/post HTTP/1.1
content-type: application/json

{
    "name": "mama",
    "age": 420
}

### find
GET http://localhost:3000/api/getOne/65efb787a6f9a056e81397e8

### Update by id
PATCH  http://localhost:3000/api/update/65efb787a6f9a056e81397e8
content-type: application/json

{
    "name": "updated",
    "age": 1234
}

### Delete
DELETE  http://localhost:3000/api/delete/65efb787a6f9a056e81397e8
